package executor

import (
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strings"
	"sync"
	"syscall"
	"time"
	"wifi-astra/internal/logging"
)

type Process struct {
	ID        string    `json:"id"`
	Command   string    `json:"command"`
	Args      []string  `json:"args"`
	PID       int       `json:"pid"`
	StartTime time.Time `json:"start_time"`
	Status    string    `json:"status"`
	LogFile   string    `json:"log_file"`
	ExitCode  int       `json:"exit_code"`
	cmd       *exec.Cmd
	cancel    context.CancelFunc
	logFH     *os.File // closed after cmd.Wait() to avoid fd leak
}

type Manager struct {
	processes map[string]*Process
	mu        sync.RWMutex
}

func NewManager() *Manager {
	return &Manager{
		processes: make(map[string]*Process),
	}
}

// displayVarPrefixes lists env var name prefixes that contain ANSI/terminal display
// codes. These are internally generated or system-provided and safe to pass through
// unsanitized — stripping semicolons from ANSI codes like \x1b[33;1m breaks them.
var displayVarPrefixes = []string{
	"ASTRA_COLOR_",
	"LS_COLORS",
	"LESS_TERMCAP_",
	"COLORTERM",
	"TERM",
}

func isDisplayVar(key string) bool {
	for _, pfx := range displayVarPrefixes {
		if key == pfx || strings.HasPrefix(key, pfx) {
			return true
		}
	}
	return false
}

// internalSafeVars are env vars generated by the controller (not user input)
// and must not be pipe-stripped — their values contain controlled characters
// (e.g. | delimiters in HMAC scope tokens like moduleID|bssid|expiry|hmac_hex).
var internalSafeVars = []string{
	"ASTRA_SCOPE_TOKEN",
}

func isInternalSafeVar(key string) bool {
	for _, v := range internalSafeVars {
		if key == v {
			return true
		}
	}
	return false
}

// SanitizeEnv strips dangerous shell metacharacters from environment variable values
// and logs a warning for any value that was modified. The KEY= prefix is preserved.
// Display/color variables (ANSI codes) are passed through unchanged.
func SanitizeEnv(env []string) []string {
	sanitized := make([]string, len(env))
	re := strings.NewReplacer(
		";", "",
		"&", "",
		"|", "",
		"`", "",
		"(", "",
		")", "",
		"\n", "",
		"\r", "",
		"<", "",
		">", "",
	)
	for i, entry := range env {
		// Preserve KEY= prefix; only sanitize the value portion
		idx := strings.IndexByte(entry, '=')
		if idx < 0 {
			sanitized[i] = entry
			continue
		}
		key := entry[:idx]
		val := entry[idx+1:]
		// Skip sanitization for display/color vars — ANSI codes contain semicolons
		if isDisplayVar(key) {
			sanitized[i] = entry
			continue
		}
		// Internal safe vars are controller-generated (not user input); only strip
		// null bytes to prevent injection via NUL, but preserve delimiters like |.
		if isInternalSafeVar(key) {
			clean := strings.ReplaceAll(val, "\x00", "")
			if clean != val {
				logging.Warn("SanitizeEnv: stripped null bytes from internal var %s", key)
			}
			sanitized[i] = key + "=" + clean
			continue
		}
		clean := re.Replace(val)
		if clean != val {
			logging.Warn("SanitizeEnv: stripped dangerous characters from env var %s (original len=%d, clean len=%d)", key, len(val), len(clean))
		}
		sanitized[i] = key + "=" + clean
	}
	return sanitized
}

// Run executes a command in the foreground and waits for it to finish.
func (m *Manager) Run(ctx context.Context, id, command string, args []string, logFile string) (int, error) {
	return m.RunWithEnv(ctx, id, command, args, logFile, os.Environ())
}

// RunWithEnv executes a command in the foreground with a custom environment.
func (m *Manager) RunWithEnv(ctx context.Context, id, command string, args []string, logFile string, env []string) (int, error) {
	logging.Info("Executing: %s %v", command, args)

	p, err := m.start(ctx, id, command, args, logFile, SanitizeEnv(env))
	if err != nil {
		return -1, err
	}

	err = p.cmd.Wait()
	if p.logFH != nil {
		p.logFH.Close()
	}
	m.mu.Lock()
	defer m.mu.Unlock()

	p.Status = "completed"
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			p.ExitCode = exitErr.ExitCode()
			p.Status = fmt.Sprintf("failed (exit code %d)", p.ExitCode)
		} else {
			p.Status = fmt.Sprintf("error: %v", err)
			return -1, err
		}
	} else {
		p.ExitCode = 0
	}

	delete(m.processes, p.ID)
	return p.ExitCode, nil
}

// Spawn executes a command in the background.
func (m *Manager) Spawn(ctx context.Context, id, command string, args []string, logFile string) (*Process, error) {
	return m.SpawnWithEnv(ctx, id, command, args, logFile, os.Environ())
}

// SpawnWithEnv executes a command in the background with a custom environment.
func (m *Manager) SpawnWithEnv(ctx context.Context, id, command string, args []string, logFile string, env []string) (*Process, error) {
	logging.Info("Spawning background process: %s %v", command, args)
	p, err := m.start(ctx, id, command, args, logFile, SanitizeEnv(env))
	if err != nil {
		return nil, err
	}

	go func() {
		err := p.cmd.Wait()
		if p.logFH != nil {
			p.logFH.Close()
		}
		m.mu.Lock()
		defer m.mu.Unlock()

		if err != nil {
			if exitErr, ok := err.(*exec.ExitError); ok {
				p.ExitCode = exitErr.ExitCode()
				p.Status = fmt.Sprintf("failed (exit code %d)", p.ExitCode)
			} else {
				p.Status = fmt.Sprintf("error: %v", err)
			}
		} else {
			p.Status = "completed"
			p.ExitCode = 0
		}
	}()

	return p, nil
}

func (m *Manager) start(ctx context.Context, id, command string, args []string, logFile string, env []string) (*Process, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if id == "" {
		id = fmt.Sprintf("proc_%d", time.Now().UnixNano())
	}

	if _, exists := m.processes[id]; exists {
		return nil, fmt.Errorf("process with ID %s already exists", id)
	}

	innerCtx, cancel := context.WithCancel(ctx)
	cmd := exec.CommandContext(innerCtx, command, args...)
	cmd.Env = env

	// Create a new process group so we can kill children properly
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}

	var logFH *os.File
	if logFile != "" {
		f, err := os.OpenFile(logFile, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0644)
		if err == nil {
			logFH = f
			cmd.Stdout = io.MultiWriter(os.Stdout, f)
			cmd.Stderr = io.MultiWriter(os.Stderr, f)
		} else {
			logging.Error("Could not open log file %s: %v", logFile, err)
			cmd.Stdout = os.Stdout
			cmd.Stderr = os.Stderr
		}
	} else {
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
	}
	cmd.Stdin = os.Stdin // Enable interactive input for modules

	if err := cmd.Start(); err != nil {
		cancel()
		return nil, err
	}

	p := &Process{
		ID:        id,
		Command:   command,
		Args:      args,
		PID:       cmd.Process.Pid,
		StartTime: time.Now(),
		Status:    "running",
		LogFile:   logFile,
		cmd:       cmd,
		cancel:    cancel,
		logFH:     logFH,
	}

	m.processes[id] = p
	return p, nil
}

// KillGroup sends SIGKILL to the process group of the given PID.
func KillGroup(pid int) {
	pgid, err := syscall.Getpgid(pid)
	if err == nil {
		logging.Debug("Sending SIGKILL to process group %d", pgid)
		syscall.Kill(-pgid, syscall.SIGKILL)
	}
}

// Stop sends SIGTERM then SIGKILL to a process and its group.
func (m *Manager) Stop(id string) error {
	m.mu.Lock()
	p, exists := m.processes[id]
	if !exists {
		m.mu.Unlock()
		return nil // Idempotent
	}
	m.mu.Unlock()

	logging.Info("Stopping process %s (PID: %d) gracefully...", id, p.PID)

	// Kill the entire process group
	pgid, err := syscall.Getpgid(p.PID)
	if err == nil {
		// Send SIGTERM to the process group
		syscall.Kill(-pgid, syscall.SIGTERM)

		// Give it a moment to die gracefully (up to 2 seconds for reports)
		for i := 0; i < 20; i++ {
			time.Sleep(100 * time.Millisecond)
			if !isProcessRunning(p.PID) {
				break
			}
		}

		// If it's still there, force it with SIGKILL
		if isProcessRunning(p.PID) {
			logging.Warn("Process %s (PID: %d) still running after SIGTERM, sending SIGKILL", id, p.PID)
			syscall.Kill(-pgid, syscall.SIGKILL)
		}
	}

	// Cancel the context to stop the executor's Wait()
	p.cancel()

	m.mu.Lock()
	delete(m.processes, id)
	m.mu.Unlock()

	return nil
}

func isProcessRunning(pid int) bool {
	process, err := os.FindProcess(pid)
	if err != nil {
		return false
	}
	// On Unix-like systems, FindProcess always succeeds.
	// We need to send signal 0 to check if the process exists.
	err = process.Signal(syscall.Signal(0))
	return err == nil
}

func (m *Manager) Cleanup() {
	m.mu.Lock()
	defer m.mu.Unlock()

	for id, p := range m.processes {
		logging.Debug("Cleanup: Killing process %s (PID: %d)", id, p.PID)
		KillGroup(p.PID)
		p.cancel()
		delete(m.processes, id)
	}
}

// GetTerminalEmulator returns the binary and arguments for the best available terminal
func (m *Manager) GetTerminalEmulator(title string) (string, []string) {
	terminals := []struct {
		bin  string
		args []string
	}{
		// Standard -e is more reliable for passing a single script path
		{"qterminal", []string{"-e"}},
		{"xfce4-terminal", []string{"-e"}},
		{"xterm", []string{"-e"}},
		{"gnome-terminal", []string{"--"}},
	}

	for _, t := range terminals {
		if path, err := exec.LookPath(t.bin); err == nil {
			return path, t.args
		}
	}
	return "", nil
}
