#!/usr/bin/env bash
#===============================================================================
#  lib/report.sh — Report Generator
#  
#  Generates both TXT and HTML assessment reports from completed test results.
#===============================================================================

set -uo pipefail

generate_report() {
    local completed
    completed=$(get_completed_count)
    local total=${#TC_ORDER[@]}
    
    if [[ $completed -eq 0 ]]; then
        log_warn "No tests completed yet. Run some tests first."
        [[ ${HEADLESS_MODE:-0} -eq 0 ]] && safe_read "Press Enter to return to menu..." _
        return
    fi
    
    echo ""
    echo -e "${C_CYAN}╔══════════════════════════════════════════════════════════════════╗${C_RESET}"
    echo -e "${C_CYAN}║  REPORT GENERATION — ${completed}/${total} tests completed                      ║${C_RESET}"
    echo -e "${C_CYAN}╚══════════════════════════════════════════════════════════════════╝${C_RESET}"
    echo ""
    
    local txt_report="${SESSION_REPORT_DIR}/assessment_report.txt"
    local html_report="${SESSION_REPORT_DIR}/assessment_report.html"
    local pdf_report="${SESSION_REPORT_DIR}/assessment_report.pdf"
    
    # Generate TXT report (Keeping Bash logic for now as it is simple)
    _generate_txt_report "$txt_report"
    
    # NEW: Generate HTML report via Assessment Engine
    log_info "Requesting HTML report from assessment engine..."
    if ! run_engine_api POST "/v1/report/generate?output=${html_report}" >/dev/null; then
        log_error "Assessment engine failed to generate HTML report."
    fi

    # Generate PDF report from the HTML generated by Go
    _generate_pdf_report "$html_report" "$pdf_report"
    
    echo ""
    log_success "Reports generated:"
    log_info "  TXT:  ${txt_report}"
    log_info "  HTML: ${html_report}"
    [[ -f "$pdf_report" ]] && log_info "  PDF:  ${pdf_report}"
    log_info "  Evidence: ${SESSION_EVIDENCE_DIR}/"
    echo ""
    [[ ${HEADLESS_MODE:-0} -eq 0 ]] && safe_read "Press Enter to return to menu..." _
}

#--- TXT Report ---
_generate_txt_report() {
    local output="$1"
    
    {
        echo "==============================================================================="
        echo "  WIFI SEGREGATION ASSESSMENT REPORT"
        echo "==============================================================================="
        echo ""
        echo "  Session ID:     ${SESSION_ID}"
        echo "  Generated:      $(date '+%Y-%m-%d %H:%M:%S')"
        echo "  Target SSID:    ${GUEST_SSID:-Not recorded}"
        echo "  Target BSSID:   ${GUEST_BSSID:-Not recorded}"
        echo "  Gateway:        ${GATEWAY_IP:-Not recorded}"
        echo "  Assigned IP:    ${MY_IP:-Not recorded}"
        echo ""
        echo "==============================================================================="
        echo "  EXECUTIVE SUMMARY"
        echo "==============================================================================="
        echo ""
        
        # Count findings
        local findings=0
        local secure=0
        local critical=0
        
        for _tc in "${TC_ORDER[@]}"; do
            if [[ "${TC_STATUS[$_tc]:-}" == "done" ]]; then
                local result_file
                result_file=$(get_tc_result_file "$_tc")
                if [[ -f "$result_file" ]]; then
                    local status
                    status=$(run_tool jq -r '.status // "INFO"' "$result_file" 2>/dev/null || echo "INFO")
                    case "${status^^}" in
                        "CRITICAL")
                            ((findings++)) || true
                            ((critical++)) || true
                            ;;
                        "FINDING"|"FAIL")
                            ((findings++)) || true
                            ;;
                        "SECURE")
                            ((secure++)) || true
                            ;;
                    esac

                fi
            fi
        done
        
        echo "  Completed Tests: ${completed}/${total}"
        echo "  Security Findings: ${findings} (${critical} critical)"
        echo "  Secure Controls: ${secure}"
        echo ""
        echo "==============================================================================="
        echo "  DETAILED RESULTS"
        echo "==============================================================================="
        echo ""

        for _tc in "${TC_ORDER[@]}"; do
            if [[ "${TC_STATUS[$_tc]:-}" == "done" ]]; then
                local tc_name
                tc_name=$(get_tc_field "$_tc" "name")
                local result_file
                result_file=$(get_tc_result_file "$_tc")
                
                if [[ -f "$result_file" ]]; then
                    local status summary details
                    status=$(run_tool jq -r '.status // "INFO"' "$result_file" 2>/dev/null || echo "INFO")
                    summary=$(run_tool jq -r '.summary // "N/A"' "$result_file" 2>/dev/null || echo "N/A")
                    
                    echo "  [${_tc}] ${tc_name}"
                    echo "  Status:  ${status}"
                    echo "  Summary: ${summary}"
                    echo "  -----------------------------------------------------------------------"
                fi
            fi
        done
        
        echo ""
        echo "  End of Report."
    } > "$output"
}

#--- PDF Report ---
_generate_pdf_report() {
    local html_input="$1"
    local pdf_output="$2"
    
    local wk_path="${TOOL_PATHS[wkhtmltopdf]:-}"
    
    if [[ -z "$wk_path" ]]; then
        wk_path=$(command -v wkhtmltopdf 2>/dev/null || echo "")
    fi
    
    if [[ -z "$wk_path" ]] || [[ ! -x "$wk_path" ]]; then
        return 0
    fi
    
    log_info "Generating PDF report..."
    
    local cmd=(
        "$wk_path"
        "--quiet"
        "--page-size" "Letter"
        "--margin-top" "20mm"
        "--margin-bottom" "20mm"
        "--enable-local-file-access"
        "$html_input"
        "$pdf_output"
    )

    if "${cmd[@]}" 2>/dev/null; then
        log_success "PDF report generated."
    fi
}

#--- Session info display ---
show_session_info() {
    echo ""
    echo -e "${C_CYAN}╔══════════════════════════════════════════════════════════════════╗${C_RESET}"
    echo -e "${C_CYAN}║  SESSION INFORMATION                                            ║${C_RESET}"
    echo -e "${C_CYAN}╚══════════════════════════════════════════════════════════════════╝${C_RESET}"
    echo ""
    echo -e "  ${C_BOLD}Session ID:${C_RESET}       ${SESSION_ID}"
    echo -e "  ${C_BOLD}Session Dir:${C_RESET}      ${SESSION_DIR}"
    echo -e "  ${C_BOLD}Evidence Dir:${C_RESET}     ${SESSION_EVIDENCE_DIR}"
    echo -e "  ${C_BOLD}Log Dir:${C_RESET}          ${SESSION_LOG_DIR}"
    echo -e "  ${C_BOLD}Report Dir:${C_RESET}       ${SESSION_REPORT_DIR}"
    echo ""
    echo -e "  ${C_BOLD}Network Configuration:${C_RESET}"
    echo -e "    WiFi Interface:   ${WIFI_INTERFACE:-Not set}"
    echo -e "    Monitor Mode:     ${MONITOR_INTERFACE:-Not active}"
    echo -e "    Target SSID:      ${GUEST_SSID:-Not set}"
    echo -e "    Target BSSID:     ${GUEST_BSSID:-Not set}"
    echo -e "    Gateway IP:       ${GATEWAY_IP:-Not set}"
    echo -e "    Our IP:           ${MY_IP:-Not set}"
    echo -e "    DNS Server:       ${DNS_SERVER:-Not set}"
    echo ""
}
